# This file sets up a production ready Cells echo-system with opiniated configuration.
#  
# It exposes 2 services via HTTPS:
#
#  The Traefik dashboard: 
# - dashboard.example.com
# - login: admin | admin 
# - secured via Let's Encrypt 
#
#  The Cells server 
# - cells.example.com
# - provided certs in default store

# Do not forget to prepare / reset acme.json file when changing the LE config,
# typically at first start or when switching from staging to prod CA server:
# touch acme.json; chmod 600 acme.json

version: "3.7"

# networks:
#   dmz:
#     external: true
#   backend:
#     external: false
#     name: backend

volumes:
    cells_working_dir: {}
    cells_data: {}
    cells_mysql_data: {}

services:
  reverse:
    image: traefik:v2.2.1
    restart: unless-stopped
    command:
      # More logs when debugging
      - --log.level=DEBUG
      # Tell traefik to watch docker events for hot reload
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      # Add a file provider to declare user provided certificates
      #- --providers.file.filename=/etc/traefik/config.yml
      - --providers.file.directory=/providers
      # Enable the dashboard on https
      - --api
      # Listen default HTTP ports
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --serverstransport.insecureskipverify=true
      # Automatic generation of certificate with Let's Encrypt: we use this to generate a LE cert for the dashboard
      - --certificatesresolvers.leresolver.acme.email=${TLS_MAIL_ADDRESS}
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
      # Insure to use staging CA server while testing to avoid being black listed => generated cert is un-trusted by browsers. Comment out once everything is correctly configured. 
      - --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Add a file provider to declare provided certificates
      - ./certs.yml:/providers/certs.yml:ro
      # Mount a folder that contains the user provided certificates
      - ./certs:/etc/traefik/certs
      # Persists certificate locally, otherwise we will recreate new ones at each restarts and quickly hit limits.
      # Remember to flush the file if you want to switch from staging CA server to prod
      - ./acme.json:/acme.json
    labels:
      # Redirect HTTP traffic to HTTPS
      - traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.redirs.entrypoints=web
      - traefik.http.routers.redirs.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      # Expose the traefik dashboard on a dedicated subdomain with HTTPS provided by a LE cert.
      - traefik.http.routers.reverse.rule=Host(`${TRAEFIK_DASHBOARD_DN}`)
      - traefik.http.routers.reverse.service=api@internal
      - traefik.http.routers.reverse.tls.certresolver=leresolver
      - traefik.http.routers.reverse.entrypoints=websecure
      # Protect dashboard with simple auth => log with admin / admin for this example
      - traefik.http.routers.reverse.middlewares=admin
      # Password is generated with `htpasswd -nb admin admin` beware to escape all '$' replacing them by '$$'
      - "traefik.http.middlewares.admin.basicauth.users=admin:$$apr1$$KnKvATsN$$L8K.P.maCu4zR/rVzD8h0/"
    # networks:
    #   - dmz

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - cells_mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=cells
      - MYSQL_USER=${MYSQL_PYDIO_USER_LOGIN}
      - MYSQL_PASSWORD=${MYSQL_PYDIO_USER_PASSWORD}
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    # networks:
    #   - backend

  cells:
    image: pydio/cells-enterprise:latest
    restart: unless-stopped
    hostname: ${CELLS_HOSTNAME}
    domainname: ${CELLS_DOMAIN}
    expose:
      - 443
    volumes:
      - cells_working_dir:/var/cells
      - cells_data:/data
      - ./pydio-license:/var/cells/pydio-license:ro
    environment:
      - CELLS_WORKING_DIR=/var/cells
      - CELLS_DATA=/data
      - CELLS_BIND=${CELLS_PUBLIC_DN}:443
      - CELLS_EXTERNAL=https://${CELLS_PUBLIC_DN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.cells.rule=Host(`${CELLS_PUBLIC_DN}`)
      - traefik.http.services.cells.loadbalancer.server.scheme=https
      - traefik.http.routers.cells.entrypoints=websecure
      - traefik.http.routers.cells.tls=true
#    networks:
#        - dmz
#        - backend
    depends_on:
      - mysql
